startDelaySecs: 5
ssl: false
blacklistObjectNames: ["java.lang:*"]
rules:
  # Route level
  - pattern: 'org.apache.camel<context=([^,]+), type=routes, name="([^"]+)"><>LastExchangeCompletedTimestamp'
    name: org.apache.camel.LastExchangeCompletedTimestamp
    help: Exchanges Last Completed Timestamps
    type: UNTYPED
    labels:
      context: $1
      route: $2
      type: routes
  - pattern: 'org.apache.camel<context=([^,]+), type=routes, name="([^"]+)"><>LastExchangeFailureTimestamp'
    name: org.apache.camel.LastExchangeFailureTimestamp
    help: Exchanges Last Failure Timestamps
    type: UNTYPED
    labels:
      context: $1
      route: $2
      type: routes
  - pattern: 'org.apache.camel<context=([^,]+), type=routes, name="([^"]+)"><>ExchangesCompleted'
    name: org.apache.camel.ExchangesCompleted
    help: Exchanges Completed
    type: COUNTER
    labels:
      context: $1
      route: $2
      type: routes
  - pattern: 'org.apache.camel<context=([^,]+), type=routes, name="([^"]+)"><>ExchangesFailed'
    name: org.apache.camel.ExchangesFailed
    help: Exchanges Failed
    type: COUNTER
    labels:
      context: $1
      route: $2
      type: routes
  - pattern: 'org.apache.camel<context=([^,]+), type=routes, name="([^"]+)"><>FailuresHandled'
    name: org.apache.camel.FailuresHandled
    help: Failures Handled
    labels:
      context: $1
      route: $2
      type: routes
    type: COUNTER
  - pattern: 'org.apache.camel<context=([^,]+), type=routes, name="([^"]+)"><>UptimeMillis'
    name: org.apache.camel.UptimeMillis
    help: Uptime Milliseconds
    type: UNTYPED
    labels:
      context: $1
      route: $2
      type: routes
